package costproductmaster

import (
	"context"
	"errors"
	"testing"
	"time"

	domain "github.com/mutugading/goapps-backend/services/finance/internal/domain/costproductmaster"
	cptdomain "github.com/mutugading/goapps-backend/services/finance/internal/domain/costproducttype"
)

// stubTypeRepo resolves both by id and by code so the create guard and the importer guard
// can share one double. Unknown lookups return cptdomain.ErrNotFound.
type stubTypeRepo struct {
	byCode map[string]int32
}

func (s *stubTypeRepo) Create(context.Context, *cptdomain.CostProductType) error { return nil }

func (s *stubTypeRepo) GetByID(_ context.Context, id int32) (*cptdomain.CostProductType, error) {
	for code, cid := range s.byCode {
		if cid == id {
			return cptdomain.Reconstruct(id, code, code, true, time.Time{}, time.Time{}), nil
		}
	}
	return nil, cptdomain.ErrNotFound
}

func (s *stubTypeRepo) GetByCode(_ context.Context, code string) (*cptdomain.CostProductType, error) {
	id, ok := s.byCode[code]
	if !ok {
		return nil, cptdomain.ErrNotFound
	}
	return cptdomain.Reconstruct(id, code, code, true, time.Time{}, time.Time{}), nil
}

func (s *stubTypeRepo) Update(context.Context, *cptdomain.CostProductType) error { return nil }

func (s *stubTypeRepo) List(context.Context, cptdomain.Filter) ([]*cptdomain.CostProductType, int64, error) {
	return nil, 0, nil
}

func (s *stubTypeRepo) ListAllActive(context.Context) ([]*cptdomain.CostProductType, error) {
	return nil, nil
}

var _ cptdomain.Repository = (*stubTypeRepo)(nil)

// TestAsyncImport_resolveTypeCode_RejectsMB pins the bulk-importer side door shut. The
// spreadsheet is a manual, user-triggered mass write path, so an MB row must be refused with
// the same sentinel the single-row create uses — MB products come only from MB Recipe
// auto-generation.
func TestAsyncImport_resolveTypeCode_RejectsMB(t *testing.T) {
	types := &stubTypeRepo{byCode: map[string]int32{"MB": 7, "YARN": 2, "FG": 3}}
	h := NewAsyncImportHandler(nil, types, nil)

	tests := []struct {
		name     string
		typeCode string
		wantErr  error
		wantID   int32
	}{
		{name: "MB is refused", typeCode: "MB", wantErr: domain.ErrMBProductNotManuallyCreatable},
		{name: "lowercase mb is refused too", typeCode: "mb", wantErr: domain.ErrMBProductNotManuallyCreatable},
		{name: "MB with surrounding space is refused", typeCode: "  MB  ", wantErr: domain.ErrMBProductNotManuallyCreatable},
		{name: "a non-MB type resolves normally", typeCode: "YARN", wantID: 2},
		{name: "another non-MB type resolves normally", typeCode: "FG", wantID: 3},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			cache := map[string]int32{}
			gotID, err := h.resolveTypeCode(context.Background(), tc.typeCode, cache)
			if tc.wantErr != nil {
				if !errors.Is(err, tc.wantErr) {
					t.Fatalf("want %v, got %v", tc.wantErr, err)
				}
				if gotID != 0 {
					t.Fatalf("a refused row must not yield a type id, got %d", gotID)
				}
				return
			}
			if err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
			if gotID != tc.wantID {
				t.Fatalf("want type id %d, got %d", tc.wantID, gotID)
			}
		})
	}
}

// TestAsyncImport_resolveTypeCode_MBNotCacheable makes sure a warm cache cannot smuggle an MB
// row through: the guard runs before the cache lookup, so a poisoned cache entry (or a code
// cached by an earlier successful row) never bypasses it.
func TestAsyncImport_resolveTypeCode_MBNotCacheable(t *testing.T) {
	types := &stubTypeRepo{byCode: map[string]int32{"MB": 7}}
	h := NewAsyncImportHandler(nil, types, nil)

	cache := map[string]int32{"MB": 7}
	if _, err := h.resolveTypeCode(context.Background(), "MB", cache); !errors.Is(err, domain.ErrMBProductNotManuallyCreatable) {
		t.Fatalf("want domain.ErrMBProductNotManuallyCreatable even with a warm cache, got %v", err)
	}
}

// TestUpdate_LeavesProductTypeAlone pins the deliberate limit of the guard: the rule is
// "a row must not BECOME MB-typed", not "an MB product is untouchable". Existing MB products
// (auto-generated by MB Recipe, plus legacy rows) must stay editable, and the update path is
// safe precisely because it never writes cpm_product_type_id — the proto and the domain both
// treat the type as immutable. If someone ever adds a type field to Update, this test fails
// and the guard must be extended to cover it.
func TestUpdate_LeavesProductTypeAlone(t *testing.T) {
	const mbTypeID, yarnTypeID = 7, 2

	tests := []struct {
		name   string
		typeID int32
	}{
		{name: "an MB product stays editable", typeID: mbTypeID},
		{name: "a non-MB product stays editable", typeID: yarnTypeID},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			p := domain.Reconstruct(
				11, "PRD-011", tc.typeID,
				"before", "SH1", "AX", "desc",
				"", "", "", nil, "",
				true,
				time.Time{}, "seed", time.Time{}, "seed",
				"", "", "", "",
				"", false,
			)

			err := p.Update("after", "SH2", "BX", "desc2", "", "", "", "editor")
			if err != nil {
				t.Fatalf("editing must not be blocked: %v", err)
			}
			if p.ProductTypeID() != tc.typeID {
				t.Fatalf("Update must not change the product type: want %d, got %d", tc.typeID, p.ProductTypeID())
			}
			if p.ProductName() != "after" {
				t.Fatalf("the edit did not apply, got %q", p.ProductName())
			}
		})
	}
}
