// Package postgres provides PostgreSQL implementations for domain repositories.
package postgres

import (
	"context"
	"database/sql"
	"fmt"
	"strconv"

	"github.com/google/uuid"

	"github.com/mutugading/goapps-backend/services/finance/internal/domain/costproductparameter"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/costroute"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/mbcomposition"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/mbhead"
	"github.com/mutugading/goapps-backend/services/finance/internal/domain/mbspin"
)

// mbCostProductTypeCode is the cost_product_type.cpt_type_code seeded (migration 000450) for
// auto-generated MB recipe products.
const mbCostProductTypeCode = "MB"

// mbCostProductSource marks cost_product_master rows auto-generated by the MB recipe workflow
// (never manually created), matching migration 000449's cpm_source column comment.
const mbCostProductSource = "MB_RECIPE"

// mst_parameter codes frozen onto an auto-generated MB cost product at Validate time, per design
// addendum §10.2 step 5. Order matches display_order in migration 000444.
const (
	paramMBWaste           = "MB_WASTE"
	paramMBQualityLoss     = "MB_QUALITY_LOSS"
	paramMBEfficiency      = "MB_EFFICIENCY"
	paramMBDevExpense      = "MB_DEV_EXPENSE"
	paramMBPacking         = "MB_PACKING"
	paramMBProdPerDay      = "MB_PROD_PER_DAY"
	paramMBThroughput      = "MB_THROUGHPUT"
	paramMBNoProcess       = "MB_NO_PROCESS"
	paramIsBoughtout       = "IS_BOUGHTOUT"
	paramMachineFixedTotal = "MACHINE_MB_FIXED_TOTAL"
	paramCompositionVer    = "MB_COMPOSITION_VERSION"
)

// mst_mb_param picklist codes whose frozen mbh_param_throughput_per_hour/mbh_param_no_of_process
// values are option codes (e.g. "B"), not numeric magnitudes — the numeric value lives on
// mst_mb_param_option and must be resolved before freezing onto CPP (data_type NUMBER).
const (
	mbpCodeThroughputPerHour = "THROUGHPUT_PER_HOUR"
	mbpCodeNoOfProcess       = "NO_OF_PROCESS"
)

// TransitionWithAutoGen performs the same work as Transition, then — only when toState is
// StatusValidated — either auto-generates the linked cost_product_master/cost_route_*/CAPP/CPP
// rows per design addendum §10.2 (first validate) or, when the cost product already exists,
// regenerates only its cost_route_rm recipe rows from the latest composition version (a later
// re-validate after an edit) so MB Batch never keeps costing off a stale, first-ever-approved
// recipe. All writes (transition + auto-gen/regen) commit or roll back together.
func (r *MBHeadRepository) TransitionWithAutoGen(ctx context.Context, id uuid.UUID, fromState, toState string, currentVersion int32, stateReason, actorUserID string, params *mbhead.ParamSnapshot, entity *mbhead.Entity) error {
	return r.db.Transaction(ctx, func(tx *sql.Tx) error {
		if err := r.updateEntryStatusTx(ctx, tx, id, fromState, toState, currentVersion, stateReason, actorUserID, params); err != nil {
			return err
		}
		if err := r.insertWorkflowLogTx(ctx, tx, id, fromState, toState, actorUserID, stateReason, currentVersion); err != nil {
			return err
		}
		if err := r.writeLockLogTx(ctx, tx, id, fromState, toState, actorUserID, stateReason); err != nil {
			return err
		}
		if toState != mbhead.StatusValidated {
			return nil
		}
		if err := r.compositionRepo.SnapshotVersion(ctx, tx, id.String(), currentVersion, actorUserID); err != nil {
			return err
		}
		if entity.CostProductID() != 0 {
			return r.regenerateCostProductRMs(ctx, tx, id, currentVersion, actorUserID, entity.CostProductID())
		}
		return r.autoGenCostProduct(ctx, tx, id, currentVersion, actorUserID, entity)
	})
}

// regenerateCostProductRMs refreshes the cost_route_rm rows under the MB's existing cost product
// route/seq when a recipe (mbhead) is re-validated after an edit. Before this fix, the linked
// cost_product_master/cost_route_head/cost_route_seq (and therefore mbh_cost_product_id) were
// generated exactly once and never touched again, so MB Batch kept costing off the FIRST approved
// composition forever, silently ignoring later edits. cost_product_master stays the same row (no
// new product, no re-linking mbh_cost_product_id) — only the recipe lines are deleted and
// re-inserted from the latest composition version, mirroring the delete-then-reinsert pattern
// already used by BulkReplaceRMs (cost_route_repository.go). mbWriteBackCostProduct's
// mbh_cost_generated_at/_by columns are refreshed too, so there is always a visible trail of when
// the copy was last regenerated instead of the number silently drifting.
func (r *MBHeadRepository) regenerateCostProductRMs(ctx context.Context, tx *sql.Tx, id uuid.UUID, version int32, actorUserID string, productSysID int64) error {
	seqID, err := mbResolveExistingRouteSeqID(ctx, tx, productSysID)
	if err != nil {
		return err
	}
	if _, err := tx.ExecContext(ctx, `DELETE FROM cost_route_rm WHERE crm_seq_id = $1`, seqID); err != nil {
		return fmt.Errorf("mb_autogen: delete stale cost_route_rm: %w", err)
	}
	rows, err := r.compositionRepo.ListVersionByMbhIDAndVersion(ctx, tx, id.String(), version)
	if err != nil {
		return err
	}
	if err := mbInsertRouteRMs(ctx, tx, seqID, productSysID, rows, actorUserID); err != nil {
		return err
	}
	return mbWriteBackCostProduct(ctx, tx, id, productSysID, actorUserID)
}

// mbResolveExistingRouteSeqID finds the single route/seq (level 1, seq 1 — the only shape
// autoGenCostProduct ever creates) under an MB's already-generated cost product, so a re-validate
// can replace its cost_route_rm rows without creating a second route or a second product.
func mbResolveExistingRouteSeqID(ctx context.Context, tx *sql.Tx, productSysID int64) (int64, error) {
	const q = `
		SELECT crs.crs_seq_id
		FROM cost_route_seq crs
		JOIN cost_route_head crh ON crh.crh_head_id = crs.crs_head_id
		WHERE crh.crh_product_sys_id = $1
		ORDER BY crs.crs_seq_id
		LIMIT 1`
	var seqID int64
	if err := tx.QueryRowContext(ctx, q, productSysID).Scan(&seqID); err != nil {
		return 0, fmt.Errorf("mb_autogen: resolve existing cost_route_seq for product %d: %w", productSysID, err)
	}
	return seqID, nil
}

// autoGenCostProduct runs the 6-step auto-gen write sequence (design addendum §10.2) inside the
// caller's transaction.
func (r *MBHeadRepository) autoGenCostProduct(ctx context.Context, tx *sql.Tx, id uuid.UUID, version int32, actorUserID string, entity *mbhead.Entity) error {
	typeID, err := mbResolveCostProductTypeID(ctx, tx)
	if err != nil {
		return err
	}
	productSysID, err := mbInsertCostProductMaster(ctx, tx, typeID, entity, actorUserID)
	if err != nil {
		return err
	}
	headID, err := mbInsertRouteHead(ctx, tx, productSysID, actorUserID)
	if err != nil {
		return err
	}
	seqID, err := mbInsertRouteSeq(ctx, tx, headID, productSysID, actorUserID)
	if err != nil {
		return err
	}
	rows, err := r.compositionRepo.ListVersionByMbhIDAndVersion(ctx, tx, id.String(), version)
	if err != nil {
		return err
	}
	if err := mbInsertRouteRMs(ctx, tx, seqID, productSysID, rows, actorUserID); err != nil {
		return err
	}
	if err := mbFreezeCostParams(ctx, tx, productSysID, entity, actorUserID); err != nil {
		return err
	}
	if err := mbWriteBackCostProduct(ctx, tx, id, productSysID, actorUserID); err != nil {
		return err
	}
	// Business-decision-driven auto-generation (confirmed by the stakeholder, not guessed):
	// right after a brand-new Master Product MB is created — first-ever Validate ONLY,
	// never on re-validate; TransitionWithAutoGen only reaches autoGenCostProduct when
	// entity.CostProductID() == 0, so this never runs a second time for the same head —
	// the system must also auto-create exactly one new MB Spin row referencing the
	// just-created product. MB Spin must NEVER be created before its Master Product MB
	// relation exists (it needs that product's ID), so this call sits strictly AFTER
	// mbWriteBackCostProduct has succeeded above, and it runs inside the SAME tx as every
	// other write in this function/TransitionWithAutoGen, so a failure here rolls back the
	// whole Lock/Validate transaction together — including the cost product and route rows.
	return mbAutoGenSpin(ctx, tx, id, entity, productSysID, actorUserID)
}

// mbAutoGenSpin creates the single MB Spin row that must exist alongside every
// first-ever-generated Master Product MB (business decision, see autoGenCostProduct's call
// site comment above — never fires on re-validate). Shade/cross-section, CC, Final Product,
// Lusture Code and (putaran 83 stakeholder decision) Denier/Filament/Dozing/MB Costing/VS
// Number are copied down from the parent MB Head's identity fields; mbs_ldr_type starts at its
// NOT_CALCULATED default (mirrors the mst_mb_spin column default) rather than being eagerly
// computed here; mbs_status starts at mbspin.StatusRnD, the same default used for
// manually-created MB Spin rows today; and the new row's cost-product linkage is set via the
// same HydrateLineage/CostProductID path the repository already uses to read that column back
// from storage (migration 000490).
func mbAutoGenSpin(ctx context.Context, tx *sql.Tx, headID uuid.UUID, entity *mbhead.Entity, productSysID int64, actorUserID string) error {
	spin, err := mbBuildAutoGenSpin(headID, entity, productSysID, actorUserID)
	if err != nil {
		return err
	}
	if err := createSpinOn(ctx, tx, spin); err != nil {
		return fmt.Errorf("mb_autogen: insert auto-generated mb spin: %w", err)
	}
	return nil
}

// mbBuildAutoGenSpin constructs (without persisting) the *mbspin.Entity that mbAutoGenSpin
// writes. Split out from mbAutoGenSpin so the field-derivation rules can be unit-tested without
// a database connection — createSpinOn (the only DB-touching step) stays in mbAutoGenSpin.
func mbBuildAutoGenSpin(headID uuid.UUID, entity *mbhead.Entity, productSysID int64, actorUserID string) (*mbspin.Entity, error) {
	mgtName := mbSpinAutoGenMgtName(entity)
	rndStatus := mbspin.StatusRnD
	mbCosting := mbEmptyStringToPtr(entity.MBCosting())
	cc := mbEmptyStringToPtr(entity.ShadeCode())

	// Stakeholder decision (putaran 83): Denier/Filament/Dozing/MB Costing/CC/Final Product
	// carry straight over from the parent MB Head — they are plain identity/spec fields with
	// no separate recalculation process, unlike the LDR fields below.
	spin, err := mbspin.New(headID, mgtName, nil, nil, entity.Denier(), entity.Filament(), entity.Dozing(), mbCosting, cc, nil, &rndStatus, nil, nil, entity.MBHFinalProduct(), nil, nil, actorUserID)
	if err != nil {
		return nil, fmt.Errorf("mb_autogen: construct auto-generated mb spin: %w", err)
	}

	// Decision D3 (31 Aug) SUPERSEDES the earlier decision from the 28 Aug session (which said
	// to leave mbs_ldr_calculated_pct blank here and rely solely on the separate LDR
	// calculation/locking process, Task E). Per D3, the calculated LDR is now seeded from the
	// MB Head at auto-gen time: prefer the head's already-recalculated run value
	// (MBHRunLdrPct), falling back to its persisted/frozen value (MBHLdrPrsn) when no run value
	// exists yet. This does NOT touch mbs_ldr_type (still LDRTypeNotCalculated, unchanged) or
	// mbs_ldr_adjustment_pct/mbs_ldr_is_actual (still nil/false) — Task E's recalculation and
	// locking flow still owns those.
	ldrCalculatedPct := entity.MBHRunLdrPct()
	if ldrCalculatedPct == nil {
		ldrCalculatedPct = entity.MBHLdrPrsn()
	}

	spin.HydrateShadeAndLDR(mbspin.ShadeAndLDR{
		ShadeCode:        mbEmptyStringToPtr(entity.ShadeCode()),
		ShadeName:        mbEmptyStringToPtr(entity.ShadeName()),
		CrossSection:     mbEmptyStringToPtr(entity.CrossSection()),
		LDRType:          mbspin.LDRTypeNotCalculated,
		LDRCalculatedPct: ldrCalculatedPct,
		LDRIsActual:      false,
	})
	spin.HydrateVSNumber(entity.VSNumber())
	spin.HydrateLustureCode(mbEmptyStringToPtr(entity.LustureCode()))
	spin.HydrateLineage(mbspin.Lineage{CostProductID: &productSysID})

	return spin, nil
}

// mbSpinAutoGenMgtName picks the source field for the auto-generated MB Spin's required
// mbs_mgt_name. The MB Head's own management name (MgtName) is the most sensible source —
// it is the human-facing display name for the recipe this spin is generated from — but it is
// optional (*string, may be nil or "" on legacy/partial heads), and mbspin.New rejects an
// empty mgtName. MBCosting is used as the fallback: unlike MgtName it is validated non-empty
// by mbhead.New/mbhead's own constructor, so it is always a safe, real (not fabricated) value
// to fall back to, and it is still a readable identifier for the recipe.
func mbSpinAutoGenMgtName(entity *mbhead.Entity) string {
	if entity.MgtName() != nil && *entity.MgtName() != "" {
		return *entity.MgtName()
	}
	return entity.MBCosting()
}

// mbEmptyStringToPtr converts one of mbhead.Entity's plain-string identity getters
// (ShadeCode/ShadeName/CrossSection) into the *string shape mbspin.ShadeAndLDR expects,
// treating an empty string as "unset" (nil) rather than as a legitimate empty value — the
// same convention already used across this file for other optional identity fields.
func mbEmptyStringToPtr(s string) *string {
	if s == "" {
		return nil
	}
	return &s
}

func mbResolveCostProductTypeID(ctx context.Context, tx *sql.Tx) (int32, error) {
	const q = `SELECT cpt_type_id FROM cost_product_type WHERE cpt_type_code = $1 AND cpt_is_active = TRUE`
	var typeID int32
	if err := tx.QueryRowContext(ctx, q, mbCostProductTypeCode).Scan(&typeID); err != nil {
		return 0, fmt.Errorf("mb_autogen: resolve cost_product_type: %w", err)
	}
	return typeID, nil
}

func mbInsertCostProductMaster(ctx context.Context, tx *sql.Tx, typeID int32, entity *mbhead.Entity, actorUserID string) (int64, error) {
	const codeQ = `SELECT generate_cost_product_code($1)`
	var code string
	if err := tx.QueryRowContext(ctx, codeQ, typeID).Scan(&code); err != nil {
		return 0, fmt.Errorf("mb_autogen: generate cost product code: %w", err)
	}

	// cpm_grade_code is written explicitly as '' (empty string) rather than omitted from the
	// column list or left as SQL NULL: the column is NOT NULL DEFAULT 'AX' (migration 000106), so
	// omitting it — or writing NULL, which violates the NOT NULL constraint outright — would let
	// the column fall through to its DB DEFAULT 'AX'. MB Recipe has no grade concept at all — the
	// value must read as empty ("—" in the UI), not the manual-entry default. cpmFromRow
	// (cost_product_master_repository.go) is the counterpart that keeps this empty value from
	// being coerced back to "AX" on read, gated on cpm_source == mbCostProductSource.
	const insertQ = `
		INSERT INTO cost_product_master
			(cpm_product_code, cpm_product_type_id, cpm_product_name, cpm_source, cpm_is_locked,
			 cpm_shade_code, cpm_shade_name, cpm_grade_code, cpm_created_by, cpm_updated_by)
		VALUES ($1, $2, $3, $4, TRUE, $5, $6, '', $7, $7)
		RETURNING cpm_product_sys_id`
	var productSysID int64
	err := tx.QueryRowContext(ctx, insertQ, code, typeID, entity.MBCosting(), mbCostProductSource,
		mbEmptyStringToPtr(entity.ShadeCode()), mbEmptyStringToPtr(entity.ShadeName()), actorUserID).Scan(&productSysID)
	if err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_product_master: %w", err)
	}
	return productSysID, nil
}

func mbInsertRouteHead(ctx context.Context, tx *sql.Tx, productSysID int64, actorUserID string) (int64, error) {
	const q = `
		INSERT INTO cost_route_head (crh_product_sys_id, crh_routing_status, crh_version, crh_created_by, crh_updated_by)
		VALUES ($1, $2, 1, $3, $3)
		RETURNING crh_head_id`
	var headID int64
	if err := tx.QueryRowContext(ctx, q, productSysID, costroute.StatusComplete, actorUserID).Scan(&headID); err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_route_head: %w", err)
	}
	return headID, nil
}

func mbInsertRouteSeq(ctx context.Context, tx *sql.Tx, headID, productSysID int64, actorUserID string) (int64, error) {
	const q = `
		INSERT INTO cost_route_seq (crs_head_id, crs_product_sys_id, crs_route_level, crs_route_seq, crs_created_by, crs_updated_by)
		VALUES ($1, $2, 1, 1, $3, $3)
		RETURNING crs_seq_id`
	var seqID int64
	if err := tx.QueryRowContext(ctx, q, headID, productSysID, actorUserID).Scan(&seqID); err != nil {
		return 0, fmt.Errorf("mb_autogen: insert cost_route_seq: %w", err)
	}
	return seqID, nil
}

func mbInsertRouteRMs(ctx context.Context, tx *sql.Tx, seqID, parentProductSysID int64, rows []VersionRow, actorUserID string) error {
	const q = `
		INSERT INTO cost_route_rm
			(crm_seq_id, crm_parent_product_sys_id, crm_rm_product_sys_id, crm_rm_group_code,
			 crm_rm_type, crm_route_rm_ratio, crm_created_by, crm_updated_by)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $7)`
	for _, row := range rows {
		pct, err := strconv.ParseFloat(row.CompositionPct, 64)
		if err != nil {
			return fmt.Errorf("mb_autogen: parse composition pct: %w", err)
		}
		if pct == 0 {
			continue
		}
		ratio := pct / 100

		var rmType string
		var rmProductSysID *int64
		var rmGroupCode *string
		if row.SourceType == mbcomposition.SourceTypeMB {
			refProductSysID, resolveErr := mbResolveRefProductSysID(ctx, tx, row.MbRefMbhID)
			if resolveErr != nil {
				return resolveErr
			}
			rmType = costroute.RmTypeProduct
			rmProductSysID = &refProductSysID
		} else {
			// GROUP and CARRIER both price through an RM group.
			groupRef, groupErr := mbGroupRef(row)
			if groupErr != nil {
				return groupErr
			}
			rmType = costroute.RmTypeGroup
			rmGroupCode = groupRef
		}

		if _, err := tx.ExecContext(ctx, q, seqID, parentProductSysID, rmProductSysID, rmGroupCode, rmType, ratio, actorUserID); err != nil {
			return fmt.Errorf("mb_autogen: insert cost_route_rm: %w", err)
		}
	}
	return nil
}

// mbGroupRef resolves the cost_route_rm.crm_rm_group_code for a composition row that
// prices through an RM group (source type GROUP or CARRIER).
//
// The empty-code rejection is the point of this function. VersionRow.GroupCode comes
// from a COALESCE(g.group_code,”) over a LEFT JOIN (mb_composition_repository.go), so
// a row whose mbcm_group_head_id is NULL — legal since migration 000459 — arrives as
// "". Writing that empty string satisfies chk_crm_one_ref and chk_crm_type_ref_match
// (migration 000222) because it is not NULL, and the resulting route line resolves to
// no RM cost at all and prices at 0 at month-end rather than raising ErrMissingRMCost.
// Carrier PBT carries real cost, so it must be priced through a group like any other
// material. Failing here surfaces the problem at Validate, where it is fixable.
func mbGroupRef(row VersionRow) (*string, error) {
	if row.GroupCode == "" {
		return nil, fmt.Errorf("mb autogen: %s row seq %d has no RM group", row.SourceType, row.SeqNo)
	}
	groupCode := row.GroupCode
	return &groupCode, nil
}

func mbResolveRefProductSysID(ctx context.Context, tx *sql.Tx, refMbhID string) (int64, error) {
	const q = `SELECT mbh_cost_product_id FROM mst_mb_head WHERE mbh_id = $1 AND deleted_at IS NULL`
	var productSysID int64
	if err := tx.QueryRowContext(ctx, q, refMbhID).Scan(&productSysID); err != nil {
		return 0, fmt.Errorf("mb_autogen: resolve nested MB cost product: %w", err)
	}
	return productSysID, nil
}

// mbOutputParamCodes are the 7 F_MB_* formulas' result_param_codes (migration 000452). They must
// be registered as CAPP rows (no CPP value — they are computed, not filled) so that LoadFormulas'
// cost_product_applicable_param join actually surfaces these formulas for the auto-generated MB
// cost product; without a CAPP row a formula is invisible to the calc engine regardless of it
// being seeded in mst_formula.
var mbOutputParamCodes = []string{
	"MB_RM_COST", "MB_WASTE_VAL", "MB_NET_PROD", "MB_FIXED_TOTAL",
	"MB_COST_OTHERS", "MB_CONV_COST", "MB_FINAL_COST",
}

// mbFreezeCostParams resolves the 11 mst_parameter IDs and upserts CAPP then CPP rows from the
// entity's already-frozen mbh_param_* values (never a runtime mst_mb_param lookup, except for the
// two picklist params whose option codes must be translated to numeric magnitudes here), then
// registers CAPP-only rows for the 7 F_MB_* formula output params so the calc engine picks them up.
func mbFreezeCostParams(ctx context.Context, tx *sql.Tx, productSysID int64, entity *mbhead.Entity, actorUserID string) error {
	throughputNumeric, err := mbResolveOptionNumericValue(ctx, tx, mbpCodeThroughputPerHour, entity.ParamThroughputPerHour())
	if err != nil {
		return err
	}
	noProcessNumeric, err := mbResolveOptionNumericValue(ctx, tx, mbpCodeNoOfProcess, entity.ParamNoOfProcess())
	if err != nil {
		return err
	}
	machineFixedTotal, err := mbResolveMachineFixedTotal(ctx, tx, entity.MachineID())
	if err != nil {
		return err
	}
	values := mbBuildParamValues(entity, throughputNumeric, noProcessNumeric, machineFixedTotal)

	capp := make([]costproductparameter.CAPPUpsertInput, 0, len(values)+len(mbOutputParamCodes))
	cpp := make([]costproductparameter.CPPUpsertInput, 0, len(values))
	now := entity.CreatedAt()
	for _, v := range values {
		paramID, resolveErr := mbResolveParamID(ctx, tx, v.code)
		if resolveErr != nil {
			return resolveErr
		}
		if shapeErr := costproductparameter.EnsureValueShape(v.dataType, v.valueNumericStr, v.valueTextStr, v.valueFlag); shapeErr != nil {
			return fmt.Errorf("mb_autogen: param %s: %w", v.code, shapeErr)
		}
		capp = append(capp, costproductparameter.CAPPUpsertInput{ProductSysID: productSysID, ParamID: paramID, IsRequired: true})
		numeric, parseErr := mbParseOptionalFloat(v.valueNumericStr)
		if parseErr != nil {
			return parseErr
		}
		cpp = append(cpp, costproductparameter.CPPUpsertInput{
			ProductSysID: productSysID, ParamID: paramID,
			ValueNumeric: numeric, ValueText: v.valueTextStr, ValueFlag: v.valueFlag,
			FilledAt: now, FilledBy: actorUserID,
		})
	}
	for _, code := range mbOutputParamCodes {
		paramID, resolveErr := mbResolveParamID(ctx, tx, code)
		if resolveErr != nil {
			return resolveErr
		}
		capp = append(capp, costproductparameter.CAPPUpsertInput{ProductSysID: productSysID, ParamID: paramID, IsRequired: false})
	}

	if _, _, err := upsertCAPPBatch(ctx, tx, capp, actorUserID, now); err != nil {
		return fmt.Errorf("mb_autogen: upsert capp: %w", err)
	}
	if _, _, err := upsertCPPBatch(ctx, tx, cpp, actorUserID, now); err != nil {
		return fmt.Errorf("mb_autogen: upsert cpp: %w", err)
	}
	return nil
}

type mbParamValue struct {
	code            string
	dataType        string
	valueNumericStr *string
	valueTextStr    *string
	valueFlag       *bool
}

func mbBuildParamValues(entity *mbhead.Entity, throughputNumeric, noProcessNumeric, machineFixedTotal *string) []mbParamValue {
	isBoughtout := entity.IsBoughtout()
	compositionVersion := strconv.FormatInt(int64(entity.CurrentVersion()), 10)

	return []mbParamValue{
		{code: paramMBWaste, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamWaste()},
		{code: paramMBQualityLoss, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamQualityLoss()},
		{code: paramMBEfficiency, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamEfficiency()},
		{code: paramMBDevExpense, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamDevExpense()},
		{code: paramMBPacking, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamPacking()},
		{code: paramMBProdPerDay, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: entity.ParamMBProdPerDay()},
		{code: paramMBThroughput, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: throughputNumeric},
		{code: paramMBNoProcess, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: noProcessNumeric},
		{code: paramIsBoughtout, dataType: string(costproductparameter.DataTypeBoolean), valueFlag: &isBoughtout},
		{code: paramMachineFixedTotal, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: machineFixedTotal},
		{code: paramCompositionVer, dataType: string(costproductparameter.DataTypeNumber), valueNumericStr: &compositionVersion},
	}
}

// mbResolveOptionNumericValue translates a frozen mst_mb_param picklist option code (e.g.
// throughput_per_hour="B") into its mst_mb_param_option.mbpo_numeric_value magnitude, which is
// what CPP must store for these two params (data_type NUMBER). Returns nil if code is empty.
func mbResolveOptionNumericValue(ctx context.Context, tx *sql.Tx, paramCode, optionCode string) (*string, error) {
	if optionCode == "" {
		return nil, nil //nolint:nilnil // absent selection is a legitimate "not set" signal, not an error
	}
	const q = `
		SELECT mbpo_numeric_value FROM mst_mb_param_option
		WHERE mbpo_mbp_code = $1 AND mbpo_code = $2 AND deleted_at IS NULL`
	var numeric float64
	if err := tx.QueryRowContext(ctx, q, paramCode, optionCode).Scan(&numeric); err != nil {
		return nil, fmt.Errorf("mb_autogen: resolve mst_mb_param_option %s/%s: %w", paramCode, optionCode, err)
	}
	v := strconv.FormatFloat(numeric, 'f', -1, 64)
	return &v, nil
}

// mbResolveMachineFixedTotal resolves MACHINE_MB_FIXED_TOTAL from the head's assigned machine
// (mst_machine.mc_tot_fxd_cst). Returns nil if no machine is assigned yet or the machine has no
// fixed-cost figure set — CAPP's IsRequired:true then correctly blocks VALIDATE until a machine
// with a fixed cost is picked, rather than silently freezing a fake 0.
func mbResolveMachineFixedTotal(ctx context.Context, tx *sql.Tx, machineID *uuid.UUID) (*string, error) {
	if machineID == nil {
		return nil, nil //nolint:nilnil // no machine assigned yet — legitimate "not set"
	}
	const q = `SELECT mc_tot_fxd_cst FROM mst_machine WHERE mc_id = $1 AND deleted_at IS NULL`
	var v sql.NullFloat64
	if err := tx.QueryRowContext(ctx, q, *machineID).Scan(&v); err != nil {
		return nil, fmt.Errorf("mb_autogen: resolve mst_machine %s: %w", *machineID, err)
	}
	if !v.Valid {
		return nil, nil //nolint:nilnil // machine has no fixed-cost figure set
	}
	s := strconv.FormatFloat(v.Float64, 'f', -1, 64)
	return &s, nil
}

func mbParseOptionalFloat(s *string) (*float64, error) {
	if s == nil {
		return nil, nil //nolint:nilnil // absent value is a legitimate "not set" signal, not an error
	}
	v, err := strconv.ParseFloat(*s, 64)
	if err != nil {
		return nil, fmt.Errorf("mb_autogen: parse numeric param: %w", err)
	}
	return &v, nil
}

func mbResolveParamID(ctx context.Context, tx *sql.Tx, code string) (uuid.UUID, error) {
	const q = `SELECT id FROM mst_parameter WHERE param_code = $1 AND deleted_at IS NULL`
	var id uuid.UUID
	if err := tx.QueryRowContext(ctx, q, code).Scan(&id); err != nil {
		return uuid.Nil, fmt.Errorf("mb_autogen: resolve mst_parameter %s: %w", code, err)
	}
	return id, nil
}

func mbWriteBackCostProduct(ctx context.Context, tx *sql.Tx, id uuid.UUID, productSysID int64, actorUserID string) error {
	const q = `
		UPDATE mst_mb_head
		SET mbh_cost_product_id = $2, mbh_cost_generated_at = NOW(), mbh_cost_generated_by = $3
		WHERE mbh_id = $1 AND deleted_at IS NULL`
	if _, err := tx.ExecContext(ctx, q, id, productSysID, actorUserID); err != nil {
		return fmt.Errorf("mb_autogen: write back cost product: %w", err)
	}
	return nil
}
