package postgres

import (
	"context"
	"database/sql"
	"fmt"

	appmbhead "github.com/mutugading/goapps-backend/services/finance/internal/application/mbhead"
	domainmbhead "github.com/mutugading/goapps-backend/services/finance/internal/domain/mbhead"
	rmcostdomain "github.com/mutugading/goapps-backend/services/finance/internal/domain/rmcost"
)

// MBCostCalcDetailExportRepository serves the flat MB cost-calculation detail dump.
//
// ⛔ READ-ONLY BY CONTRACT. This type owns exactly one SELECT and holds no write method.
//
// ⛔ It is a SEPARATE type from MBRecipeFullExportRepository on purpose: that repository
// owns recipeFullQuery, which backs the 37-column recipe export and must stay
// byte-for-byte unchanged. Nothing here touches it.
type MBCostCalcDetailExportRepository struct {
	db *DB
}

// NewMBCostCalcDetailExportRepository creates a new MBCostCalcDetailExportRepository.
func NewMBCostCalcDetailExportRepository(db *DB) *MBCostCalcDetailExportRepository {
	return &MBCostCalcDetailExportRepository{db: db}
}

var _ appmbhead.CostCalcDetailReader = (*MBCostCalcDetailExportRepository)(nil)

// costCalcDetailQuery explodes each MB head's persisted cost snapshot into one row per
// RM line: head -> cost_product_master -> ONE cst_product_cost snapshot (JOIN LATERAL
// LIMIT 1) -> jsonb_array_elements(cpc_rm_cost_detail).
//
// ============================ ROW GRAIN (the fan-out fix) ============================
// EXACTLY ONE row per (MB head, RM line of the selected snapshot). Three separate
// multiplication sources are closed off, each of which was independently proven in
// production to inflate the dump ~5x (4192 MBs -> 108090 rows instead of 21813):
//
//  1. ⛔ mst_mb_composition is NEVER joined. The RM lines of THIS report come from the
//     frozen cpc_rm_cost_detail JSONB array of the selected cost snapshot, not from the
//     live working-set recipe. Joining the composition table multiplies every cost row
//     by n_composition_rows AND reports today's recipe against a historical calc.
//  2. ⭐ EXACTLY ONE cst_product_cost row is chosen, via JOIN LATERAL ... LIMIT 1.
//     uk_cpc_active is unique only on (cpc_product_sys_id, cpc_period,
//     cpc_calculation_type) WHERE cpc_status != 'SUPERSEDED', so SEVERAL PERIODS are
//     simultaneously non-SUPERSEDED for the same product. A join with only
//     "cpc_status != 'SUPERSEDED'" therefore returns ~one row PER PERIOD — this is the
//     dominant fan-out factor.
//  3. The two lookup joins are provably 1:1 — cst_rm_group_head has a unique index on
//     group_code WHERE deleted_at IS NULL (matched by the join's own predicate) and
//     cst_rm_cost has a unique index on (period, rm_code).
//
// ============================== PERIOD SELECTION (D) ================================
// ⭐ The period is resolved ONCE, GLOBALLY, in the target_period CTE — never per head.
// A per-head "ORDER BY cpc_period DESC LIMIT 1" silently produced a workbook whose rows
// straddled several periods, and rates/tiers differ per period, so such a dump is not
// comparable to anything. When $2 is non-empty it is used VERBATIM. When $2 is empty the
// CTE picks MAX(cpc_period) across the whole table for the requested calc type — one
// period for the entire export, and the chosen period is the same for every MB.
//
// ⭐ EVERY MB-level number comes from cpc_param_snapshot, the frozen map the calc engine
// persisted. ⛔ The MB aggregates are NEVER recomputed by summing the RM lines: the
// stored aggregate is authoritative and legitimately diverges from SUM(contribution)
// when an RM line's rate was missing at calc time (in the reference dataset the sum
// matches for only 2315 of 4188 MBs — e.g. CSTMB2607000012 has an RM line whose
// unit_cost is 0). Deriving would silently corrupt those rows. ⛔ Never SUM(cost_actual).
//
// =============================== MB IDENTITY (A) ====================================
// ⭐ mb_code is cost_product_master.cpm_product_code — the CSTMB<YYMM><NNNNNN> code
// generated by generate_cost_product_code() for the type-MB product (migration 000450
// seeds cost_product_type 'MB'). ⛔ It is NOT mst_mb_head.mbh_mb_costing: that column
// holds the Oracle recipe NAME ("ALLOY GREY TR-712-A"), and a production lookup of
// mbh_mb_costing = 'CSTMB2607000001' returns ZERO rows. The target file pairs
// CSTMB2607000001 with the name ALLOY GREY TR-712-A, so mbh_mb_costing is the mb_NAME
// column, and mbh_mgt_name ("Alloy Grey BR") is a third, different string that belongs
// in neither. cost_product_master is joined INNER: an MB with no linked cost product has
// no cost snapshot either and cannot appear in a cost dump.
//
// ⭐ The RM-group name resolves through cst_rm_group_head.group_code -> .group_name.
// ⛔ There is no mbcm_rm_group_code / rm_group_code / rm_group_name column anywhere:
// mst_mb_composition references a group by the UUID mbcm_group_head_id, and the group
// head's own columns are group_code / group_name. The GROUP-type ref_code written into
// cpc_rm_cost_detail is cost_route_rm.crm_rm_group_code, which IS a group_code value —
// so joining ref_code -> group_code is the correct and only resolution path.
//
// ⭐ The tier columns are read RAW here — flag_valuation_used (the tier the RM cost
// engine ACTUALLY applied and persisted), valuation_flag_v2 (the configured flag) and the
// six per-tier rates — and resolved in Go by resolveRMRateTier.
//
// ⭐ PRODUCTION-VERIFIED (periods 202607/202608/202609, 1050 cst_rm_cost rows):
// valuation_flag_v2 is NULL on EVERY row, while flag_valuation_used already carries the
// V2 vocabulary (SL 425 / PR 214 / FL 160 / CL 137 / NONE 114) and NOT ONE legacy V1
// label (no CONS/STORES/DEPT/PO_*). Spot checks confirm cost_val equals the rate column
// flag_valuation_used names. So flag_valuation_used IS the authoritative tier and MUST be
// selected; re-deriving from the all-NULL valuation_flag_v2 mislabels every row. The
// V1-label guard in resolveRMRateTier is kept anyway — it is the whole reason the
// re-derive was written, and it is what makes reading this column safe.
//
// has_rm_cost distinguishes "no cst_rm_cost row matched" from "matched, all columns
// NULL". PRODUCT-type refs never match a cst_rm_cost row (their ref_code is
// "product:<id>", see costcalc.rmRefCode), so has_rm_cost is false for them and their
// tier renders blank.
//
// ===================== row_no: A PRESENTATION ORDINAL, BY DECISION ====================
// row_no is a DENSE PER-PERIOD ORDINAL read from the numeric suffix of cpm_product_code
// (CSTMB<YYMM><NNNNNN>), so it runs 1..N within the exported period. It is a row number
// for humans reading the sheet — ⛔ NOT an id, NOT a key, nothing is looked up by it. The
// column was called "seq" until it was renamed, because "seq" kept inviting the question
// "which id is this?".
//
// ⚠ CONSEQUENCE, STATED PLAINLY: this column does NOT match the reference export's seq
// values and is not meant to. CSTMB2607000001 gets 1 here where the reference file shows
// 52939. That is a DECISION, not a defect. Do not "fix" it.
//
// ⭐ RESOLVED — where the reference file's seq actually came from. It IS reproducible from
// this database: it is cost_route_seq.crs_seq_id. Proof: the production sequence
// cost_route_seq_crs_seq_id_seq has last_value = 57931, exactly the reference file's
// max(seq) (recon/production.txt:135). Mechanism: one transaction per MB Validate advances
// cpm_product_sys_id, crh_head_id and crs_seq_id in lockstep (mb_autogen_repository.go:
// 268-284), and mbInsertRouteSeq (:449-459) inserts exactly ONE cost_route_seq row per MB
// product — which is why crs_seq_id looks like a per-MB id. The 801-wide "gap" at the
// 2607/2608 boundary is real interleaved NON-MB cost_route_seq traffic
// (cost_import_resolve.go:418; cost_route_repository.go:66, 377, 1251, 1457).
//
// ⛔ AND THE REFERENCE FILE IS NOT A LEGACY-ORACLE ARTIFACT — an earlier version of this
// comment claimed the per-period bases "belong to the legacy system" and were "not
// derivable from this schema". Both claims were FALSE. The file was authored 2026-08-20,
// after this Postgres system was live: it is an ad-hoc query against THIS database.
//
// ⛔ crs_seq_id IS DELIBERATELY NOT USED HERE. Three independent reasons:
//  1. It is UNSTABLE. cost_route_repository.go:364 DELETEs and reinserts cost_route_seq
//     rows, burning and reassigning ids — production holds 34,219 live rows against a
//     57,931 counter (~23.7k ids burned). Exporting it would publish a number that
//     silently changes under recalculation.
//  2. Nothing consumes it. This column is WRITE-ONLY end to end (repository -> handler ->
//     browser download); no import path reads it back, and there is no
//     ImportMBCostCalcDetail among the finance service's 23 Import* RPCs.
//  3. The real business key is mb_code, which this export already carries.
//
// ⛔ DEAD HYPOTHESES — both were shipped, both disproven by production; do not resurrect
// either as the row_no projection:
//   - cst_product_cost.cpc_cost_id: CSTMB2607000001 -> 421776, ...002 -> 422973,
//     ...003 -> 422970, ...005 -> 388073. Wrong range AND non-monotonic (002 > 003), and
//     it moves with every recalculation.
//   - cost_product_master.cpm_product_sys_id: CSTMB2607000001 -> 36519. The MB population
//     spans 36519..41024 with ~313 gaps.
//
// TestCostCalcDetailQuery_RowNoIsPeriodOrdinal pins all of the above, including a ban on
// crs_seq_id / cost_route_seq entering this query.
//
// $1 = is_active filter or NULL (NULL disables the filter)
// $2 = period (YYYYMM), or ” to resolve ONE global latest period for the whole export
// $3 = calculation type (already defaulted by the application layer)
// $4 = cpc_status filter, or ” (empty means "any status except SUPERSEDED")
// $5 = IncludeRejected flag (bool); false excludes heads whose mbh_entry_status is $6
// $6 = the literal workflow-status value excluded when $5 is false
const costCalcDetailQuery = `
WITH target_period AS (
    SELECT CASE
        WHEN $2::text <> '' THEN $2::text
        ELSE (
            SELECT MAX(x.cpc_period)
            FROM cst_product_cost x
            WHERE x.cpc_calculation_type = $3
              AND ($4::text = '' OR x.cpc_status = $4::text)
              AND ($4::text <> '' OR x.cpc_status <> 'SUPERSEDED')
        )
    END AS period
)
SELECT
    p.cpm_product_code,
    h.mbh_mb_costing,
    (pc.cpc_param_snapshot ->> 'MACHINE_MB_FIXED_TOTAL')::float8,
    (pc.cpc_param_snapshot ->> 'MB_WASTE')::float8,
    (pc.cpc_param_snapshot ->> 'MB_QUALITY_LOSS')::float8,
    (pc.cpc_param_snapshot ->> 'MB_EFFICIENCY')::float8,
    (pc.cpc_param_snapshot ->> 'MB_DEV_EXPENSE')::float8,
    (pc.cpc_param_snapshot ->> 'MB_PACKING')::float8,
    (pc.cpc_param_snapshot ->> 'MB_PROD_PER_DAY')::float8,
    (pc.cpc_param_snapshot ->> 'MB_THROUGHPUT')::float8,
    (pc.cpc_param_snapshot ->> 'MB_NO_PROCESS')::float8,
    (pc.cpc_param_snapshot ->> 'MB_NET_PROD')::float8,
    (pc.cpc_param_snapshot ->> 'MB_WASTE_VAL')::float8,
    (pc.cpc_param_snapshot ->> 'MB_FIXED_TOTAL')::float8,
    (pc.cpc_param_snapshot ->> 'MB_COST_OTHERS')::float8,
    (pc.cpc_param_snapshot ->> 'MB_RM_COST')::float8,
    (pc.cpc_param_snapshot ->> 'MB_CONV_COST')::float8,
    (pc.cpc_param_snapshot ->> 'MB_FINAL_COST')::float8,
    (pc.cpc_param_snapshot ->> 'MB_FINAL_COST')::float8,
    COALESCE(pc.cpc_version, 0),
    COALESCE(pc.cpc_status, ''),
    -- row_no: dense per-period ordinal from the numeric suffix of cpm_product_code.
    -- Presentation row number only, no base offset — see the row_no note above.
    COALESCE((substring(p.cpm_product_code FROM '([0-9]{6})$'))::bigint, 0)
        AS row_no,
    COALESCE(d.elem ->> 'rm_type', ''),
    COALESCE(d.elem ->> 'ref_code', ''),
    g.group_name,
    (d.elem ->> 'ratio')::float8,
    (d.elem ->> 'unit_cost')::float8,
    (d.elem ->> 'contribution')::float8,
    rc.valuation_flag_v2,
    rc.flag_valuation_used,
    (rc.rm_code IS NOT NULL) AS has_rm_cost,
    rc.cl_rate, rc.sl_rate, rc.fl_rate, rc.cr_rate, rc.sr_rate, rc.pr_rate
FROM mst_mb_head h
CROSS JOIN target_period tp
JOIN cost_product_master p
       ON p.cpm_product_sys_id = h.mbh_cost_product_id
JOIN LATERAL (
    SELECT x.cpc_cost_id, x.cpc_version, x.cpc_status, x.cpc_period,
           x.cpc_param_snapshot, x.cpc_rm_cost_detail
    FROM cst_product_cost x
    WHERE x.cpc_product_sys_id = h.mbh_cost_product_id
      AND x.cpc_calculation_type = $3
      AND x.cpc_period = tp.period
      AND ($4::text = '' OR x.cpc_status = $4::text)
      AND ($4::text <> '' OR x.cpc_status <> 'SUPERSEDED')
    ORDER BY x.cpc_version DESC, x.cpc_cost_id DESC
    LIMIT 1
) pc ON TRUE
CROSS JOIN LATERAL jsonb_array_elements(
    CASE WHEN jsonb_typeof(pc.cpc_rm_cost_detail) = 'array'
         THEN pc.cpc_rm_cost_detail
         ELSE '[]'::jsonb
    END
) WITH ORDINALITY AS d(elem, ord)
LEFT JOIN cst_rm_group_head g
       ON g.group_code = (d.elem ->> 'ref_code') AND g.deleted_at IS NULL
LEFT JOIN cst_rm_cost rc
       ON rc.rm_code = (d.elem ->> 'ref_code') AND rc.period = pc.cpc_period
WHERE h.deleted_at IS NULL
  AND tp.period IS NOT NULL
  AND ($1::boolean IS NULL OR h.mbh_is_active = $1::boolean)
  AND ($5::boolean OR h.mbh_entry_status != $6)
ORDER BY p.cpm_product_code ASC, d.ord ASC`

// costCalcDetailSkippedQuery is the OBSERVABILITY twin of costCalcDetailQuery: it names
// the MB heads that pass every one of that query's filters and select the very same cost
// snapshot, but contribute ZERO rows to the dump because that snapshot's
// cpc_rm_cost_detail is an EMPTY array.
//
// ⭐ WHY IT IS A SECOND QUERY AND NOT A CHANGE TO THE FIRST. costCalcDetailQuery flattens
// the JSONB array with CROSS JOIN LATERAL jsonb_array_elements, so a head with zero RM
// lines produces zero rows and is simply absent from the result — the repository returns
// only flattened RM rows, so the handler cannot possibly tell WHICH heads were dropped.
// Turning that CROSS JOIN into a LEFT JOIN would surface them, but it would also change
// the emitted row set: the dump emits 21813 rows for period 202607 and that number matches
// the reference workbook EXACTLY. ⛔ So costCalcDetailQuery is not touched at all, and the
// skip count comes from this separate, cheap read instead.
//
// ⛔ IT PROJECTS ONLY mb_code. It feeds a log line, nothing else, and nothing it returns
// ever reaches the workbook.
//
// ⭐ THE PREDICATES ARE A VERBATIM COPY of costCalcDetailQuery's — the same target_period
// CTE, the same cost_product_master INNER JOIN, the same JOIN LATERAL ... LIMIT 1 snapshot
// pick, and the same WHERE clause. They MUST stay in lockstep: a head counted as "skipped"
// that the dump would never have considered in the first place is a false alarm.
// TestCostCalcDetailSkippedQuery_MirrorsTheDumpsPredicates pins this.
//
// ⚠ SCOPE, STATED PLAINLY: this counts the EMPTY-ARRAY case only — a head that HAS a
// matching snapshot whose RM-line array is empty. It deliberately keeps the INNER
// JOIN LATERAL, so a head with NO matching snapshot at all is not counted here; that is a
// different (and differently caused) absence. The non-array case cannot error either way:
// both queries wrap the column in the same jsonb_typeof guard.
//
// Production case this exists for: CSTMB2609000099 ("TW0509 50% TIO2 PBT MASTERBATCH") —
// VALIDATED, active, version 9, an APPROVED 202607/ACTUAL cost row, a route head and a
// route sequence, but zero route RMs and zero RM lines on all 21 of its cost rows.
//
// $1..$6 are IDENTICAL to costCalcDetailQuery's.
const costCalcDetailSkippedQuery = `
WITH target_period AS (
    SELECT CASE
        WHEN $2::text <> '' THEN $2::text
        ELSE (
            SELECT MAX(x.cpc_period)
            FROM cst_product_cost x
            WHERE x.cpc_calculation_type = $3
              AND ($4::text = '' OR x.cpc_status = $4::text)
              AND ($4::text <> '' OR x.cpc_status <> 'SUPERSEDED')
        )
    END AS period
)
SELECT p.cpm_product_code
FROM mst_mb_head h
CROSS JOIN target_period tp
JOIN cost_product_master p
       ON p.cpm_product_sys_id = h.mbh_cost_product_id
JOIN LATERAL (
    SELECT x.cpc_cost_id, x.cpc_version, x.cpc_status, x.cpc_period,
           x.cpc_param_snapshot, x.cpc_rm_cost_detail
    FROM cst_product_cost x
    WHERE x.cpc_product_sys_id = h.mbh_cost_product_id
      AND x.cpc_calculation_type = $3
      AND x.cpc_period = tp.period
      AND ($4::text = '' OR x.cpc_status = $4::text)
      AND ($4::text <> '' OR x.cpc_status <> 'SUPERSEDED')
    ORDER BY x.cpc_version DESC, x.cpc_cost_id DESC
    LIMIT 1
) pc ON TRUE
WHERE h.deleted_at IS NULL
  AND tp.period IS NOT NULL
  AND ($1::boolean IS NULL OR h.mbh_is_active = $1::boolean)
  AND ($5::boolean OR h.mbh_entry_status != $6)
  AND COALESCE(jsonb_array_length(
        CASE WHEN jsonb_typeof(pc.cpc_rm_cost_detail) = 'array'
             THEN pc.cpc_rm_cost_detail
             ELSE '[]'::jsonb
        END), 0) = 0
ORDER BY p.cpm_product_code ASC`

// ListCostCalcDetailSkippedMBCodes names the MB heads the dump silently drops because
// their selected cost snapshot has an EMPTY cpc_rm_cost_detail array.
//
// ⛔ OBSERVABILITY ONLY: a separate read that never influences ListCostCalcDetailRows.
func (r *MBCostCalcDetailExportRepository) ListCostCalcDetailSkippedMBCodes(
	ctx context.Context, filter appmbhead.CostCalcDetailFilter,
) ([]string, error) {
	var active sql.NullBool
	if filter.IsActive != nil {
		active = sql.NullBool{Bool: *filter.IsActive, Valid: true}
	}

	// ⚠ Argument order MUST match costCalcDetailQuery's, placeholder for placeholder.
	rows, err := r.db.QueryContext(
		ctx, costCalcDetailSkippedQuery, active, filter.Period, filter.CalculationType,
		filter.CalcStatus, filter.IncludeRejected, domainmbhead.StatusRejected,
	)
	if err != nil {
		return nil, fmt.Errorf("mb_cost_calc_detail_export_repository: list skipped mb codes: %w", err)
	}
	defer closeRows(rows)

	var out []string
	for rows.Next() {
		var mbCode string
		if scanErr := rows.Scan(&mbCode); scanErr != nil {
			return nil, fmt.Errorf("mb_cost_calc_detail_export_repository: scan skipped mb code: %w", scanErr)
		}
		out = append(out, mbCode)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("mb_cost_calc_detail_export_repository: iterate skipped mb codes: %w", err)
	}
	return out, nil
}

// ListCostCalcDetailRows executes the calc-detail read. One row per (MB head, RM line).
func (r *MBCostCalcDetailExportRepository) ListCostCalcDetailRows(
	ctx context.Context, filter appmbhead.CostCalcDetailFilter,
) ([]appmbhead.CostCalcDetailRow, error) {
	var active sql.NullBool
	if filter.IsActive != nil {
		active = sql.NullBool{Bool: *filter.IsActive, Valid: true}
	}

	// ⚠ Argument order MUST match the $N placeholders: $1 active, $2 period, $3 calc
	// type, $4 calc status, $5 include-rejected flag, $6 the workflow-status literal.
	rows, err := r.db.QueryContext(
		ctx, costCalcDetailQuery, active, filter.Period, filter.CalculationType,
		filter.CalcStatus, filter.IncludeRejected, domainmbhead.StatusRejected,
	)
	if err != nil {
		return nil, fmt.Errorf("mb_cost_calc_detail_export_repository: list rows: %w", err)
	}
	defer closeRows(rows)

	var out []appmbhead.CostCalcDetailRow
	for rows.Next() {
		row, scanErr := scanCostCalcDetailRow(rows)
		if scanErr != nil {
			return nil, scanErr
		}
		out = append(out, row)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("mb_cost_calc_detail_export_repository: iterate rows: %w", err)
	}
	return out, nil
}

// costCalcDetailDTO mirrors costCalcDetailQuery's column list one-for-one. Every
// nullable column is a sql.Null* so absence survives into the application row as nil
// rather than collapsing to a fabricated 0 (D13).
type costCalcDetailDTO struct {
	// MBCode is cost_product_master.cpm_product_code (CSTMB2607000001...), MBName is
	// mst_mb_head.mbh_mb_costing (the Oracle recipe name, "ALLOY GREY TR-712-A").
	// ⛔ Not the other way round — see costCalcDetailQuery's MB IDENTITY note.
	MBCode string
	MBName sql.NullString

	TotalFix, PctWaste, PctQualityLoss  sql.NullFloat64
	PctEfficiency, DevExpense, Packing  sql.NullFloat64
	ProdPerDay, ThroughputPerHr         sql.NullFloat64
	NoProcess                           sql.NullFloat64
	MBNetProd, MBWasteVal, MBFixedTotal sql.NullFloat64
	MBCostOthers, MBRMCost, MBConvCost  sql.NullFloat64
	MBTotalCost, MBCostPerUnit          sql.NullFloat64

	CalcVersion int32
	CalcStatus  string
	RowNo       int64

	RMType, RMRef                 string
	RMGroupName                   sql.NullString
	Komposisi, RMRate, CostActual sql.NullFloat64

	// Raw tier inputs, resolved in Go by resolveRMRateTier.
	// FlagValuationUsed is the tier the RM cost engine actually applied and persisted —
	// authoritative when it holds a V2 label (see resolveRMRateTier's precedence).
	// HasRMCost is false when no cst_rm_cost row matched at all (PRODUCT-type rows).
	ValuationFlagV2        sql.NullString
	FlagValuationUsed      sql.NullString
	HasRMCost              bool
	CLRate, SLRate, FLRate sql.NullFloat64
	CRRate, SRRate, PRRate sql.NullFloat64
}

func scanCostCalcDetailRow(rows *sql.Rows) (appmbhead.CostCalcDetailRow, error) {
	var d costCalcDetailDTO
	err := rows.Scan(
		&d.MBCode, &d.MBName,
		&d.TotalFix, &d.PctWaste, &d.PctQualityLoss, &d.PctEfficiency,
		&d.DevExpense, &d.Packing, &d.ProdPerDay, &d.ThroughputPerHr, &d.NoProcess,
		&d.MBNetProd, &d.MBWasteVal, &d.MBFixedTotal, &d.MBCostOthers,
		&d.MBRMCost, &d.MBConvCost, &d.MBTotalCost, &d.MBCostPerUnit,
		&d.CalcVersion, &d.CalcStatus, &d.RowNo,
		&d.RMType, &d.RMRef, &d.RMGroupName,
		&d.Komposisi, &d.RMRate, &d.CostActual,
		&d.ValuationFlagV2, &d.FlagValuationUsed, &d.HasRMCost,
		&d.CLRate, &d.SLRate, &d.FLRate, &d.CRRate, &d.SRRate, &d.PRRate,
	)
	if err != nil {
		return appmbhead.CostCalcDetailRow{}, fmt.Errorf("mb_cost_calc_detail_export_repository: scan row: %w", err)
	}

	return appmbhead.CostCalcDetailRow{
		MBCode:          d.MBCode,
		MBName:          nullStrPtr(d.MBName),
		TotalFix:        nullFloatPtr(d.TotalFix),
		PctWaste:        nullFloatPtr(d.PctWaste),
		PctQualityLoss:  nullFloatPtr(d.PctQualityLoss),
		PctEfficiency:   nullFloatPtr(d.PctEfficiency),
		DevExpense:      nullFloatPtr(d.DevExpense),
		Packing:         nullFloatPtr(d.Packing),
		ProdPerDay:      nullFloatPtr(d.ProdPerDay),
		ThroughputPerHr: nullFloatPtr(d.ThroughputPerHr),
		NoProcess:       nullFloatPtr(d.NoProcess),
		MBNetProd:       nullFloatPtr(d.MBNetProd),
		MBWasteVal:      nullFloatPtr(d.MBWasteVal),
		MBFixedTotal:    nullFloatPtr(d.MBFixedTotal),
		MBCostOthers:    nullFloatPtr(d.MBCostOthers),
		MBRMCost:        nullFloatPtr(d.MBRMCost),
		MBConvCost:      nullFloatPtr(d.MBConvCost),
		MBTotalCost:     nullFloatPtr(d.MBTotalCost),
		MBCostPerUnit:   nullFloatPtr(d.MBCostPerUnit),
		CalcVersion:     d.CalcVersion,
		CalcStatus:      d.CalcStatus,
		RowNo:           d.RowNo,
		RMType:          d.RMType,
		RMRef:           d.RMRef,
		RMGroupName:     nullStrPtr(d.RMGroupName),
		Komposisi:       nullFloatPtr(d.Komposisi),
		RMRateActual:    nullFloatPtr(d.RMRate),
		RMRateTier:      resolveRMRateTier(&d),
		CostActual:      nullFloatPtr(d.CostActual),
	}, nil
}

// v2ValuationLabels is the Selection Flags V2 vocabulary for the valuation tier. It is
// the GUARD that makes reading cst_rm_cost.flag_valuation_used safe: that column is
// merely VARCHAR(20) and its CHECK constraint (migrations 000472 / 000501) still admits
// the legacy V1 vocabulary (CONS/STORES/DEPT/PO_1/PO_2/PO_3/INIT) written before
// ENG-RM-01/P3. Anything outside this set is a V1 (or unknown) label and is treated as
// unusable, falling through to the re-derive/cascade below.
//
// ⛔ Do not widen this set to "whatever the CHECK constraint allows" — the whole point is
// that it is narrower than the constraint.
var v2ValuationLabels = map[string]struct{}{
	"CR": {}, "SR": {}, "PR": {},
	"CL": {}, "SL": {}, "FL": {},
	rmcostdomain.FlagNone: {},
}

// resolveRMRateTier resolves the Selection Flags V2 valuation tier for one RM line, in
// this precedence:
//
//  1. cst_rm_cost.flag_valuation_used, when non-empty AND in the V2 vocabulary
//     (CR/SR/PR/CL/SL/FL/NONE) — used DIRECTLY. This is the flag the RM cost engine
//     actually applied when it computed the persisted cost_val, so it is the truth.
//  2. else valuation_flag_v2, when non-empty — RE-DERIVED through the same cascade the
//     V2 engine uses (rmcostdomain.SelectValuationWithFlag), so an explicit configured
//     flag still resolves and a legacy/blank flag_valuation_used cannot mislabel the row.
//  3. else the AUTO cascade (CL→SL→FL→PR over the per-tier rate columns) as a last
//     resort, so a row with neither flag still gets an honest, rate-derived label.
//
// ⭐ PRODUCTION-VERIFIED, and the reason step 1 exists at all: across periods
// 202607/202608/202609 (1050 cst_rm_cost rows) valuation_flag_v2 is NULL on EVERY row
// while flag_valuation_used already holds V2 labels only — SL 425 / PR 214 / FL 160 /
// CL 137 / NONE 114, with ZERO legacy V1 labels. Spot checks confirm cost_val equals the
// rate column flag_valuation_used names (e.g. rm DYE0000015 202607: used=CL,
// cost_val=14.774611 == cl_rate=14.77461060). The previous implementation ignored this
// column and re-derived from the all-NULL valuation_flag_v2, which mislabeled every row.
//
// ⚠ The V1 guard above is deliberately KEPT even though production currently has no V1
// labels: it is the entire reason the re-derive was written, and it is what lets step 1
// trust the column. Historical rows written before ENG-RM-01/P3 may still carry
// CONS/STORES/DEPT/PO_* there, and those must fall through to step 2/3.
//
// Returns "" when the row has no cst_rm_cost match at all — that is the PRODUCT-type
// case (nested-MB references have no RM cost row), and a blank tier is the correct,
// honest rendering for it rather than a fabricated label.
//
// "NONE" (no price source existed for the period) is likewise rendered as blank, whether
// it arrived from flag_valuation_used or from the cascade: it is the engine's internal
// marker for "no source", not a tier the dump's consumers know how to read.
func resolveRMRateTier(d *costCalcDetailDTO) string {
	// No cst_rm_cost row matched at all → PRODUCT-type line, blank tier. Fall back to
	// the flag columns' NULL-ness for older callers that never set HasRMCost.
	if !d.HasRMCost && !d.ValuationFlagV2.Valid && !d.FlagValuationUsed.Valid {
		return ""
	}

	// 1. The persisted, engine-applied flag wins — when it speaks V2.
	if used := d.FlagValuationUsed.String; d.FlagValuationUsed.Valid && used != "" {
		if _, ok := v2ValuationLabels[used]; ok {
			if used == rmcostdomain.FlagNone {
				return ""
			}
			return used
		}
		// A legacy V1 (or unknown) label: unusable, fall through to 2/3.
	}

	tot := rmcostdomain.ValuationTotals{
		CR: d.CRRate.Float64, SR: d.SRRate.Float64, PR: d.PRRate.Float64,
		CL: d.CLRate.Float64, SL: d.SLRate.Float64, FL: d.FLRate.Float64,
	}

	// 2. The configured flag, re-derived through the shared cascade. 3. Otherwise AUTO.
	flag := rmcostdomain.FlagAuto
	if d.ValuationFlagV2.Valid && d.ValuationFlagV2.String != "" {
		flag = d.ValuationFlagV2.String
	}
	_, used := rmcostdomain.SelectValuationWithFlag(tot, flag)
	if used == rmcostdomain.FlagNone {
		return ""
	}
	return used
}
