#!/usr/bin/env python3
"""Generate migration 000566_seed_cost_superba_cost_sp.up.sql from the CSV.

Usage: python3 scripts/gen_superba_cost_sp_seed.py [CSV] [OUT]
Deterministic: same CSV -> byte-identical output.

Encoding: the CSV is Windows-1252, not latin-1. Row 201 holds byte 0x96 (an en
dash); latin-1 would turn it into the C1 control char U+0096, so we decode as
cp1252 and assert no control characters remain.
"""
import csv
import io
import sys
from decimal import Decimal
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_CSV = HERE.parents[3] / "docs" / "SUPERBA_COST_SP.CSV"
DEFAULT_OUT = HERE.parent / "migrations" / "postgres" / "000566_seed_cost_superba_cost_sp.up.sql"
MARK = "seed_000566"


def q(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def num(s: str) -> str:
    d = Decimal(s.strip())  # raises on garbage
    return format(d, "f")


def main() -> None:
    src = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_CSV
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else DEFAULT_OUT
    text = src.read_bytes().decode("cp1252")
    rows = list(csv.reader(io.StringIO(text, newline="")))
    header = [h.strip() for h in rows[0]]
    assert header == ["No", "Sys Id", "Shade Code", "Superba Color Name", "OLD Value", "New Value"], header

    tuples, seen = [], set()
    for r in rows[1:]:
        if not any(f.strip() for f in r):
            continue
        r = [f.strip() for f in r]
        _, sys_id, shade, colour, old, new = r
        assert sys_id.isdigit() and sys_id not in seen, sys_id
        seen.add(sys_id)
        assert shade and len(shade) <= 30, shade
        assert len(colour) <= 200
        assert all(ord(c) >= 32 and not 0x7F <= ord(c) <= 0x9F for c in colour + shade), (sys_id, colour)
        tuples.append("(%s, %s, %s, %s, %s)" % (
            sys_id, q(shade), q(colour) if colour else "NULL", num(old), num(new) if new else "NULL"))

    body = ",\n    ".join(tuples)
    sql = f"""-- 000566: seed cost_superba_cost_sp from docs/SUPERBA_COST_SP.CSV ({len(tuples)} rows).
-- GENERATED by services/finance/scripts/gen_superba_cost_sp_seed.py - do not hand edit.
-- CSV decoded as cp1252 (row 201 has an en dash, byte 0x96). All fields trimmed;
-- empty New Value -> NULL. source='SEED'.
-- Single statement => atomic under golang-migrate (no explicit BEGIN/COMMIT).
-- Re-run safe: ON CONFLICT updates only rows still owned by the seed
-- (source='SEED'); ORACLE/MANUAL rows are never clobbered.

INSERT INTO cost_superba_cost_sp AS t
    (legacy_sys_id, shade_code, colour_name, old_value, new_value, source, created_by)
SELECT v.legacy_sys_id, v.shade_code, v.colour_name::varchar, v.old_value::numeric, v.new_value::numeric, 'SEED', '{MARK}'
FROM (VALUES
    {body}
) AS v(legacy_sys_id, shade_code, colour_name, old_value, new_value)
ON CONFLICT (legacy_sys_id) DO UPDATE SET
    shade_code = EXCLUDED.shade_code,
    colour_name = EXCLUDED.colour_name,
    old_value = EXCLUDED.old_value,
    new_value = EXCLUDED.new_value,
    updated_at = NOW(),
    updated_by = '{MARK}'
WHERE t.source = 'SEED';
"""
    out.write_text(sql, encoding="utf-8")
    print(f"wrote {out} ({len(tuples)} rows)")


if __name__ == "__main__":
    main()
