-- ============================================================================
-- Purpose        : M-ERP-4a: cutover backups (creates backup tables and spools DDL; changes nothing legacy)
-- Target schema  : MGTDAT
-- M-ERP-4a: cutover backups (creates backup tables and spools DDL; changes nothing legacy)
-- Executed by    : DBA, at CUTOVER only, before M-ERP-4b/4c
-- Run as         : a user with CREATE TABLE in MGTDAT and SELECT_CATALOG_ROLE
-- Parameters     : &&PERIOD = YYYYMM (cutover period)
-- Rollback       : none; backups are kept
-- Re-runnable    : CTAS wrapped (ignore ORA-00955)
-- ============================================================================
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
SET DEFINE ON
DEFINE PERIOD = &1

-- 1. Backup of the legacy std table
BEGIN EXECUTE IMMEDIATE 'CREATE TABLE MGTDAT.OT_STD_COST_PRODUCTS_MGT_BK_&&PERIOD AS SELECT * FROM MGTDAT.OT_STD_COST_PRODUCTS_MGT';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
-- 2. Backup of the period's ADJ items (same filter as V_GOAPPS_ADJ_DEMAND)
BEGIN EXECUTE IMMEDIATE q'[CREATE TABLE MGTDAT.OT_ADJ_ITEM_BK_&&PERIOD AS
  SELECT i.* FROM MGTDAT.OT_ADJ_HEAD h JOIN MGTDAT.OT_ADJ_ITEM i ON i.ADJI_ADJH_SYS_ID = h.ADJH_SYS_ID
   WHERE h.ADJH_TXN_CODE IN ('INVADJ','MBINVADJ','MBINVADJRP')
     AND TRUNC(h.ADJH_DT) BETWEEN TO_DATE('&&PERIOD'||'01','YYYYMMDD') AND LAST_DAY(TO_DATE('&&PERIOD'||'01','YYYYMMDD'))]';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -955 THEN RAISE; END IF; END;
/
-- 3. DDL backup spool (restore source for M-ERP-4b rollback)
-- Check object types first (O_DGET_FG_ITEM_RATE_MGT may be FUNCTION or PROCEDURE):
--   SELECT OBJECT_NAME, OBJECT_TYPE FROM ALL_OBJECTS WHERE OWNER='MGTDAT' AND OBJECT_NAME IN
--     ('O_DGET_FG_ITEM_RATE_MGT','FUNC_CHIP_WAC_MGT','PRODUCTS_LIST_COST');
SET LONG 1000000 PAGESIZE 0 LINESIZE 32767 TRIMSPOOL ON FEEDBACK OFF HEADING OFF
SPOOL m_erp_4a_ddl_backup_&&PERIOD..sql
SELECT DBMS_METADATA.GET_DDL('FUNCTION',  'O_DGET_FG_ITEM_RATE_MGT','MGTDAT') FROM DUAL;  -- or 'PROCEDURE' per the check above
SELECT DBMS_METADATA.GET_DDL('FUNCTION',  'FUNC_CHIP_WAC_MGT','MGTDAT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('VIEW',      'VIEW_MARGIN_REPORT','MGTDAT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('VIEW',      'VIEW_MARGIN_REPORT_TODAY','MGTDAT') FROM DUAL;
-- T-3 (open): _DEV* variants, enable once the DBA confirms their names
-- SELECT DBMS_METADATA.GET_DDL('VIEW', 'VIEW_MARGIN_REPORT_DEV','MGTDAT') FROM DUAL;
-- SELECT DBMS_METADATA.GET_DDL('VIEW', 'VIEW_MARGIN_REPORT_TODAY_DEV','MGTDAT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('PROCEDURE', 'PRODUCTS_LIST_COST','MGTDAT') FROM DUAL;  -- or FUNCTION/VIEW per ALL_OBJECTS
SELECT DBMS_METADATA.GET_DDL('TRIGGER',   'ODBTRG_ITEMCOSTVALLOSS_MGT','MGTDAT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TRIGGER',   'ODBTRG_SELLPRICECOST_MGT','MGTDAT') FROM DUAL;
SELECT DBMS_METADATA.GET_DDL('TRIGGER',   'ODBTRG_FG_STD_COST','MGTDAT') FROM DUAL;
SPOOL OFF
SET PAGESIZE 100 FEEDBACK ON HEADING ON

-- 4. Scheduler job listing (feeds the <job name> placeholders in M-ERP-4c)
SELECT OWNER, JOB_NAME, ENABLED, STATE FROM DBA_SCHEDULER_JOBS
 WHERE UPPER(JOB_NAME) LIKE '%COST%' OR UPPER(JOB_NAME) LIKE '%WAC%' ORDER BY OWNER, JOB_NAME;
