-- ============================================================================
-- Purpose        : M-ERP-2 rollback: revoke the interface user's grants and LOCK the account.
--                  No DROP USER (no CASCADE). Affects the NEW user only. DBA ONLY.
-- Target schema  : MGTDAT
-- Executed by    : DBA (GoApps never runs this script)
-- ============================================================================
WHENEVER SQLERROR EXIT FAILURE ROLLBACK
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT ON MGTDAT.CST_GOAPPS_STD_BATCH FROM GOAPPS_IF';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1927,-1951,-1918) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE SELECT, INSERT ON MGTDAT.CST_GOAPPS_STD_COST FROM GOAPPS_IF';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1927,-1951,-1918) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'REVOKE EXECUTE ON MGTDAT.PKG_GOAPPS_ADJ FROM GOAPPS_IF';
EXCEPTION WHEN OTHERS THEN IF SQLCODE NOT IN (-1927,-1951,-1918,-942,-4042) THEN RAISE; END IF; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER USER GOAPPS_IF ACCOUNT LOCK';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -1918 THEN RAISE; END IF; END;
/
