-- 000002: intentionally a NO-OP.
--
-- This migration used to CREATE TABLE audit_logs. It must not, because in
-- staging and production finance and IAM share ONE database (`goapps`) and ONE
-- `public` schema -- see goapps-infra/services/{finance,iam}-service/base/
-- migrate-job.yaml, which both point at /goapps and differ only in
-- x-migrations-table. `audit_logs` there belongs to IAM
-- (iam/migrations/postgres/000006_create_audit_tables.up.sql), which owns a
-- different shape: log_id/event_type/user_id, plus a gRPC AuditService and the
-- /finance/../iam/audit-logs UI reading it.
--
-- Running both definitions in one schema FAILS -- verified in both orders:
--   iam first  -> this file's `CREATE INDEX ... (performed_by)` errors:
--                 column "performed_by" does not exist
--   this first -> iam's `CREATE INDEX ... (event_type)` errors:
--                 column "event_type" does not exist
-- The CREATE TABLE is skipped by IF NOT EXISTS, but the indexes after it are
-- not guarded against a different shape, so one migrate-job dies and its
-- schema_migrations_* row is left dirty.
--
-- Finance's own audit needs are already served by dedicated tables --
-- `cost_audit_log` (000215), which backs the /finance/audit-logs page via
-- ListCostAuditLogs, plus aud_cost_history, cost_param_edit_log, bi_audit_log
-- and others. Nothing in finance reads or writes `audit_logs`: the only code
-- that did was internal/infrastructure/audit, which `go list` confirmed had
-- zero importers and was never compiled into the server binary.
--
-- The file is emptied rather than renumbered or deleted on purpose. Environments
-- that already applied it recorded version 2; removing or renumbering the file
-- would desynchronize golang-migrate's version bookkeeping. Cleanup of rows
-- already created by the old body is handled forward, in 000491.
SELECT 1;
