-- Remove seeded Oracle yarn parameters.
-- Safe to run: uses param_code list, leaves other params untouched.
DELETE FROM mst_parameter
WHERE param_code IN (
  'MC_NAME','YARN_DENIER','ACT_DENIER','FILAMENT_COUNT','NO_OF_PLY',
  'CROSS_SECTION','LUSTRE_TYPE','INTERMINGLE','RM_TYPE','Y_TYPE','POLYMER_IV',
  'TPM','MC_SPEED','MC_EFFICIENCY','NO_OF_POSITION','NO_OF_END','MACHINE_RPM',
  'CHANGE_OVER_KG','VOL_BUCKET_1_QTY','VOL_BUCKET_2_QTY','VOL_BUCKET_3_QTY',
  'VOL_BUCKET_4_QTY','VOL_BUCKET_5_QTY','RAW_MATERIAL','WASTE_PCT','OPU',
  'OIL_NAME','DRAW_RATIO','RM_NORMS','AX_PERC','AE_PERC','A9_PERC','A_PERC',
  'B_PERC','C_PERC','AX_WT','AE_WT','A9_WT','A_WT','B_WT','C_WT','NET_BOB_WT',
  'CAP_PACK_CODE','CAP_NO_OF_BOB','CAP_BOX_WT','CAP_BOB_RATE','CAP_BOX_RATE',
  'CAP_PACK_COST','DEL_PACK_CODE','DEL_NO_OF_BOB','DEL_BOX_WT','DEL_BOB_RATE',
  'DEL_BOX_RATE','DEL_PACK_COST','HEATSET_CODE','NO_OF_TROLLIES','NO_BOB_PER_TROL',
  'BATCH_WEIGHT','RM_RATE','RM_LANDED_COST','OIL_RATE','OIL_COST','ELEC_KWH',
  'ELEC_RATE','LABOR_HRS','LABOR_RATE','DEPREC_PER_KG','MB_CODE','MB_DYE_NAME',
  'MB_DOZING_PCT','MB_RATE','MB_COST','RP_DOZING','INTERMINGLE_COST',
  'SPECIAL_COST_1','SPECIAL_COST_2','NET_PRODUCTION','POWER_PER_DAY',
  'MANPOWER_PER_DAY','OVERHEAD_PER_DAY','SPARES_PER_DAY','POWER_PER_KG',
  'MANPOWER_PER_KG','OVERHEAD_PER_KG','SPARES_PER_KG','TOTAL_FIXED_COST',
  'LABOR_OVERHEAD_PCT','CONV_CAP_EX_MB','CONV_DEL_EX_MB','CAP_COST_PRE_QL',
  'DEL_COST_PRE_QL','STD_LOSS_GRADE','BC_LOSS_GRADE','NON_STD_PERC','BC_PERC',
  'BC_RECOVERY_RATE','NON_STD_LOSS','BC_LOSS_CAP','BC_LOSS_DEL','QLOSS_CAP',
  'QLOSS_DEL','COST_CAP_FINAL','COST_DEL_FINAL','VB1_LOSS','VB2_LOSS','VB3_LOSS',
  'VB4_LOSS','VB5_LOSS','VB1_DEL_COST','VB2_DEL_COST','VB3_DEL_COST',
  'VB4_DEL_COST','VB5_DEL_COST','COST_STAGE_OUT',
  'STEAM_RATE','WATER_RATE','MAT_OVERHEAD_PCT',
  'HEATSET_COST_KG','COST_ELEC','COST_LABOR','COST_CONVERSION'
)
AND created_by = 'seed_000381';
