ALTER TABLE cost_erp_item
    ADD COLUMN IF NOT EXISTS cei_created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS cei_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ADD COLUMN IF NOT EXISTS cei_created_by VARCHAR(100) NOT NULL DEFAULT 'system',
    ADD COLUMN IF NOT EXISTS cei_updated_by VARCHAR(100) NOT NULL DEFAULT 'system';
