// Package costproductmaster contains the CostProductMaster domain (PRD Phase B §7.4.1, CPM_).
package costproductmaster

import (
	"errors"
	"strings"
	"time"
)

var (
	// ErrNotFound is returned when a product master is not found.
	ErrNotFound = errors.New("cost product master not found")
	// ErrAlreadyExists is returned when product_code already exists (auto-code collision).
	ErrAlreadyExists = errors.New("cost product master code already exists")
	// ErrInvalidProductName is returned when product name fails validation.
	ErrInvalidProductName = errors.New("invalid product_name (must be 1..500 chars)")
	// ErrInvalidGradeCode is returned when grade_code is empty.
	ErrInvalidGradeCode = errors.New("invalid grade_code (must be 1..20 chars)")
	// ErrInactive is returned when attempting to modify a deactivated product.
	ErrInactive = errors.New("product master is inactive")
)

// CostProductMaster is the product identity aggregate.
type CostProductMaster struct {
	productSysID   int64
	productCode    string
	productTypeID  int32
	productName    string
	shadeCode      string
	gradeCode      string
	description    string
	erpItemCode    string
	erpGradeCode1  string
	erpGradeCode2  string
	erpLinkedAt    *time.Time
	erpLinkedBy    string
	isActive       bool
	createdAt      time.Time
	createdBy      string
	updatedAt      time.Time
	updatedBy      string
}

// NewInput contains the create inputs (product_code is generated by DB).
type NewInput struct {
	ProductTypeID int32
	ProductName   string
	ShadeCode     string
	GradeCode     string
	Description   string
	ActorUserID   string
}

// New constructs a new CostProductMaster prior to insert. product_code and product_sys_id are assigned by repo.
func New(in NewInput) (*CostProductMaster, error) {
	name := strings.TrimSpace(in.ProductName)
	if name == "" || len(name) > 500 {
		return nil, ErrInvalidProductName
	}
	grade := strings.TrimSpace(in.GradeCode)
	if grade == "" {
		grade = "AX"
	}
	if len(grade) > 20 {
		return nil, ErrInvalidGradeCode
	}
	now := time.Now().UTC()
	return &CostProductMaster{
		productTypeID: in.ProductTypeID,
		productName:   name,
		shadeCode:     strings.TrimSpace(in.ShadeCode),
		gradeCode:     grade,
		description:   strings.TrimSpace(in.Description),
		isActive:      true,
		createdAt:     now,
		createdBy:     in.ActorUserID,
		updatedAt:     now,
		updatedBy:     in.ActorUserID,
	}, nil
}

// Reconstruct rebuilds an aggregate from persistence.
func Reconstruct(
	productSysID int64,
	productCode string,
	productTypeID int32,
	productName, shadeCode, gradeCode, description string,
	erpItemCode, erpGradeCode1, erpGradeCode2 string,
	erpLinkedAt *time.Time, erpLinkedBy string,
	isActive bool,
	createdAt time.Time, createdBy string,
	updatedAt time.Time, updatedBy string,
) *CostProductMaster {
	return &CostProductMaster{
		productSysID: productSysID, productCode: productCode, productTypeID: productTypeID,
		productName: productName, shadeCode: shadeCode, gradeCode: gradeCode, description: description,
		erpItemCode: erpItemCode, erpGradeCode1: erpGradeCode1, erpGradeCode2: erpGradeCode2,
		erpLinkedAt: erpLinkedAt, erpLinkedBy: erpLinkedBy,
		isActive:  isActive,
		createdAt: createdAt, createdBy: createdBy,
		updatedAt: updatedAt, updatedBy: updatedBy,
	}
}

// SetGeneratedCode is called by the repo after the DB returns the generated product_code + sys_id.
func (p *CostProductMaster) SetGeneratedCode(sysID int64, code string) {
	p.productSysID = sysID
	p.productCode = code
}

// Update mutates editable descriptive fields. product_type_id is immutable.
func (p *CostProductMaster) Update(productName, shadeCode, gradeCode, description, actor string) error {
	if !p.isActive {
		return ErrInactive
	}
	name := strings.TrimSpace(productName)
	if name == "" || len(name) > 500 {
		return ErrInvalidProductName
	}
	grade := strings.TrimSpace(gradeCode)
	if grade == "" {
		grade = p.gradeCode
	}
	if len(grade) > 20 {
		return ErrInvalidGradeCode
	}
	p.productName = name
	p.shadeCode = strings.TrimSpace(shadeCode)
	p.gradeCode = grade
	p.description = strings.TrimSpace(description)
	p.updatedAt = time.Now().UTC()
	p.updatedBy = actor
	return nil
}

// LinkErp sets/refreshes the ERP linkage. Empty erpItemCode unlinks.
func (p *CostProductMaster) LinkErp(erpItemCode, erpGradeCode1, erpGradeCode2, actor string) {
	now := time.Now().UTC()
	p.erpItemCode = strings.TrimSpace(erpItemCode)
	p.erpGradeCode1 = strings.TrimSpace(erpGradeCode1)
	p.erpGradeCode2 = strings.TrimSpace(erpGradeCode2)
	if p.erpItemCode == "" {
		p.erpLinkedAt = nil
		p.erpLinkedBy = ""
	} else {
		p.erpLinkedAt = &now
		p.erpLinkedBy = actor
	}
	p.updatedAt = now
	p.updatedBy = actor
}

// Deactivate flips the active flag off (soft-deactivate).
func (p *CostProductMaster) Deactivate(actor string) {
	if !p.isActive {
		return
	}
	p.isActive = false
	now := time.Now().UTC()
	p.updatedAt = now
	p.updatedBy = actor
}

// Read-only accessors.
func (p *CostProductMaster) ProductSysID() int64       { return p.productSysID }
func (p *CostProductMaster) ProductCode() string       { return p.productCode }
func (p *CostProductMaster) ProductTypeID() int32      { return p.productTypeID }
func (p *CostProductMaster) ProductName() string       { return p.productName }
func (p *CostProductMaster) ShadeCode() string         { return p.shadeCode }
func (p *CostProductMaster) GradeCode() string         { return p.gradeCode }
func (p *CostProductMaster) Description() string       { return p.description }
func (p *CostProductMaster) ErpItemCode() string       { return p.erpItemCode }
func (p *CostProductMaster) ErpGradeCode1() string     { return p.erpGradeCode1 }
func (p *CostProductMaster) ErpGradeCode2() string     { return p.erpGradeCode2 }
func (p *CostProductMaster) ErpLinkedAt() *time.Time   { return p.erpLinkedAt }
func (p *CostProductMaster) ErpLinkedBy() string       { return p.erpLinkedBy }
func (p *CostProductMaster) IsActive() bool            { return p.isActive }
func (p *CostProductMaster) CreatedAt() time.Time      { return p.createdAt }
func (p *CostProductMaster) CreatedBy() string         { return p.createdBy }
func (p *CostProductMaster) UpdatedAt() time.Time      { return p.updatedAt }
func (p *CostProductMaster) UpdatedBy() string         { return p.updatedBy }
