-- Extend lot_master with the yarn-specification columns carried by the legacy
-- Oracle lot master ASPAK.MMSMERGE, plus a provenance marker distinguishing an
-- ETL-imported lot from one PPC generated at work-order creation.
--
-- Every column is nullable: rows already generated by the area-based sequence
-- (workorder.FormatLotNo) carry none of this and must stay valid. The sync path
-- merges with COALESCE semantics so a PPC-local correction is never clobbered by
-- a later re-sync.

ALTER TABLE lot_master
    -- Provenance. 'PPC' = minted by the lot sequence at WO creation.
    -- 'MMSMERGE' = imported from the legacy Oracle lot master.
    ADD COLUMN IF NOT EXISTS lm_source          VARCHAR(20) NOT NULL DEFAULT 'PPC',
    -- MERGE_CODE verbatim, kept separate from lm_lot_no so a future lot-number
    -- reformat does not lose the join key back to Oracle.
    ADD COLUMN IF NOT EXISTS lm_source_key      VARCHAR(30),
    ADD COLUMN IF NOT EXISTS lm_synced_at       TIMESTAMPTZ,

    -- Yarn specification (MMSMERGE).
    ADD COLUMN IF NOT EXISTS lm_prod_type       VARCHAR(15),   -- MERGE_PROD_TYPE  PTY/POY/FOY
    ADD COLUMN IF NOT EXISTS lm_yarn_type       VARCHAR(15),   -- YARN_TYPE        PTY/POY/BSD/SD
    ADD COLUMN IF NOT EXISTS lm_denier          VARCHAR(15),   -- MERGE_DENIER     VARCHAR2 in source, kept as text
    ADD COLUMN IF NOT EXISTS lm_filament        INTEGER,       -- MERGE_FILAMENT
    ADD COLUMN IF NOT EXISTS lm_cross_section   VARCHAR(15),   -- MERGE_CROSS_SEC  RND/TBL
    ADD COLUMN IF NOT EXISTS lm_qc_grade        VARCHAR(15),   -- MERGE_QC_GRADE   AX/Aa
    ADD COLUMN IF NOT EXISTS lm_description     VARCHAR(60),   -- MERGE_DESCR      'SD HCSH NI'
    ADD COLUMN IF NOT EXISTS lm_shade_color     VARCHAR(240),  -- SHADE_COLOR, falling back to MERGE_COLOR/YARN_COLOR

    -- Packing specification.
    ADD COLUMN IF NOT EXISTS lm_tare_box_wt     DECIMAL(8,4),  -- MERGE_TARE_BOX_WT   kg, empty box
    ADD COLUMN IF NOT EXISTS lm_tare_bobbin_wt  DECIMAL(8,4),  -- MERGE_TARE_BOBIN_WT kg, empty bobbin
    ADD COLUMN IF NOT EXISTS lm_bobbins_per_box INTEGER,       -- NVL(MERGE_NOBOB, MERGE_BOX) — see note below
    -- MERGE_BOB verbatim. Read as kg per bobbin, but UNCONFIRMED: it is 5.00 on
    -- the PTY samples and 0.00 on POY/FOY, and 5.00 kg x 25 per box does not
    -- match a plausible carton weight. Stored raw and used only to seed
    -- lm_std_weight_full on first import; never to overwrite a PPC value.
    ADD COLUMN IF NOT EXISTS lm_src_bob_weight  DECIMAL(8,4),

    ADD COLUMN IF NOT EXISTS lm_orion_item_code VARCHAR(30),   -- MERGE_ITEM_ORION
    ADD COLUMN IF NOT EXISTS lm_machine_no      VARCHAR(15),   -- MERGE_MACHINE
    ADD COLUMN IF NOT EXISTS lm_efficiency_pct  INTEGER,       -- MERGE_EFF

    -- Legacy status flags kept verbatim. PPC_ORACLE_PROCEDURES.sql filters
    -- packing on NVL(MERGE_PAK_STATUS,'S') <> 'B', so the same exclusion has to
    -- be expressible here without a second Oracle round trip.
    ADD COLUMN IF NOT EXISTS lm_src_status      VARCHAR(1),    -- MERGE_STATUS
    ADD COLUMN IF NOT EXISTS lm_src_pak_status  VARCHAR(1);    -- MERGE_PAK_STATUS

-- Relax NOT NULL on the columns MMSMERGE cannot always supply.
--
-- SHADE_CODE is empty on every sampled MMSMERGE row (colour lives in
-- MERGE_COLOR / YARN_COLOR instead), and MERGE_BOB is 0.00 on the POY and FOY
-- samples, so an imported lot frequently has no shade and no usable weight.
-- Forcing a placeholder would be worse than NULL: a 0 kg standard weight reads
-- as a real answer to the ETL bobbin-quantity calculation, whereas NULL is
-- treated as "unknown" and the lot is left at qty 0 pending a PPC correction.
-- PPC-generated lots still always carry all three.
ALTER TABLE lot_master ALTER COLUMN lm_shade_code        DROP NOT NULL;
ALTER TABLE lot_master ALTER COLUMN lm_std_weight_full   DROP NOT NULL;
ALTER TABLE lot_master ALTER COLUMN lm_std_weight_unfull DROP NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'chk_lot_master_source'
    ) THEN
        ALTER TABLE lot_master
            ADD CONSTRAINT chk_lot_master_source
            CHECK (lm_source IN ('PPC', 'MMSMERGE'));
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_lot_master_source      ON lot_master (lm_source);
CREATE INDEX IF NOT EXISTS idx_lot_master_orion_item  ON lot_master (lm_orion_item_code);
CREATE INDEX IF NOT EXISTS idx_lot_master_prod_type   ON lot_master (lm_prod_type);
